baseURL = "/"
languageCode = "en-GB"
title = "So, How Is That Working For You?"

[params]
    description = "Goldsmiths Computational Arts 2019"
    author = ""
    
[menu]
    [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 1

    [[menu.main]]
    name = "artists"
    url = "/artists/"
    weight = 2

    [[menu.main]]
    name = "map"
    url = "/map/"
    weight = 3

    [[menu.main]]
    name = "info"
    url = "/info/"
    weight = 4

    [[menu.social]]
    name = "\uF082"
    url = "https://www.facebook.com/events/468722533703227/"
    weight = 1

    [[menu.social]]
    name = "\uF081"
    url = "https://twitter.com/goldcomparts/"
    weight = 2

    [[menu.social]]
    name = "\uF083"
    url = "https://www.instagram.com/goldsmithscomparts"
    weight = 3

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true