baseURL = "/"
languageCode = "en-GB"
title = "So, How Is That Working For You?"
theme = "sohow-theme"

[params]
    description = "Goldsmiths Computational Arts 2019"
    author = ""
    themes = ""

[params.social]
    [[params.social.list]]
    class = "fab"
    icon = "fa-twitter"
    url = "#"

    [[params.social.list]]
    class = "fab"
    icon = "fa-instagram"
    url = "#"

    [[params.social.list]]
    class = "fab"
    icon = "fa-facebook"
    url = "#"

    [[params.social.list]]
    class = "fab"
    icon = "fa-github"
    url = "#"
    
